# Generated by Django 5.2.15 on 2026-08-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0212_data_sync_delete_unmatched_rows'),
        ('versatile_views', '0001_versatile_view_elements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versatilecalendarelement',
            options={'verbose_name': 'Versatile Calendar element'},
        ),
        migrations.AlterModelOptions(
            name='versatilekanbanelement',
            options={'verbose_name': 'Versatile Kanban element'},
        ),
        migrations.AlterModelOptions(
            name='versatiletimelineelement',
            options={'verbose_name': 'Versatile Timeline element'},
        ),
        migrations.CreateModel(
            name='HmsCalendarView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.view')),
                ('card_cover_image_field', models.ForeignKey(blank=True, help_text='A file field whose first image is shown as the card cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_calendar_view_card_cover_field', to='database.field')),
                ('date_field', models.ForeignKey(blank=True, help_text='The date field that positions a record on the calendar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_calendar_view_date_field', to='database.field')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='HmsCalendarViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether the field should be hidden on the card.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order the field has on the card. A lower value comes first.')),
                ('calendar_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versatile_views.hmscalendarview')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
            ],
            options={
                'ordering': ('order', 'field_id'),
                'abstract': False,
                'unique_together': {('calendar_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='hmscalendarview',
            name='field_options',
            field=models.ManyToManyField(through='versatile_views.HmsCalendarViewFieldOptions', to='database.field'),
        ),
        migrations.CreateModel(
            name='HmsKanbanView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.view')),
                ('card_cover_image_field', models.ForeignKey(blank=True, help_text='A file field whose first image is shown as the card cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_kanban_view_card_cover_field', to='database.field')),
                ('single_select_field', models.ForeignKey(blank=True, help_text='The single select field that records are stacked by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_kanban_view_single_select_field', to='database.field')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='HmsKanbanViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether the field should be hidden on the card.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order the field has on the card. A lower value comes first.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('kanban_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versatile_views.hmskanbanview')),
            ],
            options={
                'ordering': ('order', 'field_id'),
                'abstract': False,
                'unique_together': {('kanban_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='hmskanbanview',
            name='field_options',
            field=models.ManyToManyField(through='versatile_views.HmsKanbanViewFieldOptions', to='database.field'),
        ),
        migrations.CreateModel(
            name='HmsListView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.view')),
                ('card_cover_image_field', models.ForeignKey(blank=True, help_text='A file field whose first image is shown as the row thumbnail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_list_view_card_cover_field', to='database.field')),
                ('group_by_field', models.ForeignKey(blank=True, help_text='An optional field that splits the list into sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_list_view_group_by_field', to='database.field')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='HmsListViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether the field should be hidden on the card.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order the field has on the card. A lower value comes first.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('list_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versatile_views.hmslistview')),
            ],
            options={
                'ordering': ('order', 'field_id'),
                'abstract': False,
                'unique_together': {('list_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='hmslistview',
            name='field_options',
            field=models.ManyToManyField(through='versatile_views.HmsListViewFieldOptions', to='database.field'),
        ),
        migrations.CreateModel(
            name='HmsTimelineView',
            fields=[
                ('view_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.view')),
                ('card_cover_image_field', models.ForeignKey(blank=True, help_text='A file field whose first image is shown as the card cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_timeline_view_card_cover_field', to='database.field')),
                ('end_date_field', models.ForeignKey(blank=True, help_text="The date field where a record's bar ends.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_timeline_view_end_date_field', to='database.field')),
                ('group_by_field', models.ForeignKey(blank=True, help_text='An optional field that splits the timeline into swimlanes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_timeline_view_group_by_field', to='database.field')),
                ('start_date_field', models.ForeignKey(blank=True, help_text="The date field where a record's bar starts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hms_timeline_view_start_date_field', to='database.field')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('database.view',),
        ),
        migrations.CreateModel(
            name='HmsTimelineViewFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=True, help_text='Whether the field should be hidden on the card.')),
                ('order', models.SmallIntegerField(default=32767, help_text='The order the field has on the card. A lower value comes first.')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('timeline_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versatile_views.hmstimelineview')),
            ],
            options={
                'ordering': ('order', 'field_id'),
                'abstract': False,
                'unique_together': {('timeline_view', 'field')},
            },
        ),
        migrations.AddField(
            model_name='hmstimelineview',
            name='field_options',
            field=models.ManyToManyField(through='versatile_views.HmsTimelineViewFieldOptions', to='database.field'),
        ),
    ]
